// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://walapugrqplrguzgojlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbGFwdWdycXBscmd1emdvamxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzUzMzYsImV4cCI6MjA2NTMxMTMzNn0.G3KIKp6pTz2pgNiFYSXvQZw57Ey8r47RTzjQeUeCAeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);